### ISSUE TITLE
App crash when click clean button

### ISSUE THREAD

**Issue by likky** [mzlogin/CleanExpert#12]
时间	设备名称	类型	PID	标记	消息
08-23 22:32:03.409	HUAWEI BLN-AL40	Error	21375	AndroidRuntime	Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at org.mazhuang.cleanexpert.task.OverallScanTask.travelPath(OverallScanTask.java:36)
	at org.mazhuang.cleanexpert.task.OverallScanTask.doInBackground(OverallScanTask.java:87)
	at org.mazhuang.cleanexpert.task.OverallScanTask.doInBackground(OverallScanTask.java:16)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by salmanashraf** [comment]
@likky any success regarding this error?
